title: My Resume
url: 'http://sittisak123.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Never Jack  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: THAILAND , THA


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
